name: second-flow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: list_step
      run: ls -ltr
      
    - name: second_step
      run: pwd

    

      
