name: test-workflow

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list files
        run: ls -ltr
    

