name: test-workflow

on:
  workflow_dispatch:
  
jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list files
        run: ls -ltr
        
      - name: Print trigger info
        run: echo "Triggered by ${{ github.event_name }}"
    

