name: test-workflow

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      GLOBAL_VAR: "Hello from job"

    steps:
      - name: Step 1 (uses GLOBAL_VAR)
        run: echo "$GLOBAL_VAR"

      - name: Step 2 (overrides with local ENV_VAR)
        env:
          LOCAL_VAR: "Hello from step"
        run: |
          echo "$GLOBAL_VAR"
          echo "$LOCAL_VAR"

      - name: Step 3 (LOCAL_VAR not available here)
        run: |
          echo "$GLOBAL_VAR"
          echo "$LOCAL_VAR"  # This will be empty
    

